enum_trailing_comma = true
fn_args_layout = "Block"
format_strings = false
match_block_trailing_comma = true
match_wildcard_trailing_comma = true
normalize_comments = false
struct_trailing_comma = "Always"
struct_lit_trailing_comma = "Always"
reorder_imports = true
reorder_imported_names = true
report_todo = "Always"
report_fixme = "Always"
where_trailing_comma = true
write_mode = "Overwrite"
